#!/bin/bash

SCRIPT_PATH=$(dirname "$0")
API_KEY=$(cat ${SCRIPT_PATH}/wmata_api_key.txt)
LOGFILE=/tmp/last_run_get_bus_positions
UTC_DAY=$(date +%Y-%m-%d)
OUTDIR=$HOME/coldstore/organized_transit_data/wmatabus/short_term/$UTC_DAY/
mkdir -p $OUTDIR
TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S)
OUTFILE=$OUTDIR/buses$TIMESTAMP.json
wget --no-check-certificate -O $OUTFILE "https://api.wmata.com/Bus.svc/json/jBusPositions?api_key=${API_KEY}"

OUTFILE_GTFSRT_VP=$OUTDIR/gtfsrt-vp-$TIMESTAMP.pb
wget --no-check-certificate -O $OUTFILE_GTFSRT_VP "https://api.wmata.com/gtfs/bus-gtfsrt-vehiclepositions.pb?api_key=${API_KEY}"

OUTFILE_GTFSRT_TU=$OUTDIR/gtfsrt-tu-$TIMESTAMP.pb
wget --no-check-certificate -O $OUTFILE_GTFSRT_TU "https://api.wmata.com/gtfs/bus-gtfsrt-tripupdates.pb?api_key=${API_KEY}"


touch $LOGFILE
